// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCALDXe28XvmCmjv_mDwK0ikGFHHtOM6s8',
    appId: '1:272219856152:web:50108bf36db0f851d2d26d',
    messagingSenderId: '272219856152',
    projectId: 'mobilepj-f89a8',
    authDomain: 'mobilepj-f89a8.firebaseapp.com',
    storageBucket: 'mobilepj-f89a8.firebasestorage.app',
    measurementId: 'G-X2J1GBHYFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyU-iKhRVgrGtEMJU_BlmFb4ZjKxpzweY',
    appId: '1:272219856152:android:3dce0c1ed0c77695d2d26d',
    messagingSenderId: '272219856152',
    projectId: 'mobilepj-f89a8',
    storageBucket: 'mobilepj-f89a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMS_yjWDudMoNJOu8dS78vFZPfgLXxTh4',
    appId: '1:272219856152:ios:38ec52f1ab134cc2d2d26d',
    messagingSenderId: '272219856152',
    projectId: 'mobilepj-f89a8',
    storageBucket: 'mobilepj-f89a8.firebasestorage.app',
    iosClientId: '272219856152-iffkah55i8hmfpnpsnm97vjlc4lndfhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsenseNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMS_yjWDudMoNJOu8dS78vFZPfgLXxTh4',
    appId: '1:272219856152:ios:38ec52f1ab134cc2d2d26d',
    messagingSenderId: '272219856152',
    projectId: 'mobilepj-f89a8',
    storageBucket: 'mobilepj-f89a8.firebasestorage.app',
    iosClientId: '272219856152-iffkah55i8hmfpnpsnm97vjlc4lndfhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsenseNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCALDXe28XvmCmjv_mDwK0ikGFHHtOM6s8',
    appId: '1:272219856152:web:a158f444306b19bad2d26d',
    messagingSenderId: '272219856152',
    projectId: 'mobilepj-f89a8',
    authDomain: 'mobilepj-f89a8.firebaseapp.com',
    storageBucket: 'mobilepj-f89a8.firebasestorage.app',
    measurementId: 'G-LZG11D3JNK',
  );
}
